default_stages: [ pre-commit ]

default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        files: ^(app)/
      - id: check-yaml
        files: ^(app)/
      - id: end-of-file-fixer
        files: ^(app)/
      - id: trailing-whitespace
        files: ^(app)/

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        files: ^(app)/
        entry: pyupgrade --py313-plus --keep-percent-format

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff
        files: ^(app)/
        args: [--fix]
      - id: ruff-format
        files: ^(app)/

  - repo: https://github.com/JacobCoffee/ty-pre-commit
    rev: v0.0.1
    hooks:
      - id: ty
        name: ty check
        args: [ "--ignore", "unresolved-import" ]

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt via uv
        entry: bash -c "uv export --format requirements-txt > requirements.txt"
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-commit ]

      - id: add-requirements
        name: Git add updated requirements.txt
        entry: bash -c "git add requirements.txt"
        language: system
        pass_filenames: false
        always_run: true
        stages: [ pre-commit ]
