services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${APP__DB__USER}
      POSTGRES_PASSWORD: ${APP__DB__PASSWORD}
      POSTGRES_DB: ${APP__DB__NAME}
    ports:
      - ${APP__DB__PORT}:5432
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql/data
